In [77]:
import pandas as pd
from sklearn.linear_model import LinearRegression

In [78]:
df = pd.read_csv('updated_yt_data.csv')
print(df)

     Video_ID  Title_Length  Upload_Hour Thumbnail_Color  Current_Subscribers  \
0           1            45           17             Red                50000
1           2            32           10            Blue                 1500
2           3            60           18             Red               300000
3           4            25            3           Green                  200
4           5            55           16             Red                12000
..        ...           ...          ...             ...                  ...
145       146            91           23          Purple                   85
146       147            53           17             Red                47000
147       148            60           10            Blue                 4200
148       149            67           15             Red                22000
149       150            27            5          Orange                  650

     Views
0    15500
1      450
2    95000
3       60
4     3800
..     ...
145     30
146  15000
147   1250
148   7100
149    210

[150 rows x 6 columns]

# Red, Blue, Green, Orange, Purple

In [79]:
new_df = df.drop('Video_ID', axis=1)
print(new_df)

     Title_Length  Upload_Hour Thumbnail_Color  Current_Subscribers  Views
0              45           17             Red                50000  15500
1              32           10            Blue                 1500    450
2              60           18             Red               300000  95000
3              25            3           Green                  200     60
4              55           16             Red                12000   3800
..            ...          ...             ...                  ...    ...
145            91           23          Purple                   85     30
146            53           17             Red                47000  15000
147            60           10            Blue                 4200   1250
148            67           15             Red                22000   7100
149            27            5          Orange                  650    210

[150 rows x 5 columns]

In [80]:
color_df = pd.get_dummies( new_df['Thumbnail_Color'], prefix='Color',  dtype=int)
print(color_df)

     Color_Blue  Color_Green  Color_Orange  Color_Purple  Color_Red
0             0            0             0             0          1
1             1            0             0             0          0
2             0            0             0             0          1
3             0            1             0             0          0
4             0            0             0             0          1
..          ...          ...           ...           ...        ...
145           0            0             0             1          0
146           0            0             0             0          1
147           1            0             0             0          0
148           0            0             0             0          1
149           0            0             1             0          0

[150 rows x 5 columns]

In [81]:
upd_df = pd.concat( [ new_df.drop('Thumbnail_Color', axis=1), color_df ], axis=1 )

print(upd_df)

     Title_Length  Upload_Hour  Current_Subscribers  Views  Color_Blue  \
0              45           17                50000  15500           0
1              32           10                 1500    450           1
2              60           18               300000  95000           0
3              25            3                  200     60           0
4              55           16                12000   3800           0
..            ...          ...                  ...    ...         ...
145            91           23                   85     30           0
146            53           17                47000  15000           0
147            60           10                 4200   1250           1
148            67           15                22000   7100           0
149            27            5                  650    210           0

     Color_Green  Color_Orange  Color_Purple  Color_Red
0              0             0             0          1
1              0             0             0          0
2              0             0             0          1
3              1             0             0          0
4              0             0             0          1
..           ...           ...           ...        ...
145            0             0             1          0
146            0             0             0          1
147            0             0             0          0
148            0             0             0          1
149            0             1             0          0

[150 rows x 9 columns]

In [83]:
upd_df.describe()

,Title_Length,Upload_Hour,Current_Subscribers,Views,Color_Blue,Color_Green,Color_Orange,Color_Purple,Color_Red
count,150.000000,150.000000,150.000000,150.000000,150.00000,150.000000,150.000000,150.000000,150.000000
mean,51.500000,13.413333,36403.666667,11523.886667,0.20000,0.166667,0.133333,0.100000,0.400000
std,19.813476,5.670111,56433.106384,18070.223219,0.40134,0.373927,0.341073,0.301005,0.491539
min,15.000000,1.000000,50.000000,15.000000,0.00000,0.000000,0.000000,0.000000,0.000000
25%,36.000000,9.250000,2025.000000,605.000000,0.00000,0.000000,0.000000,0.000000,0.000000
50%,50.000000,15.000000,11750.000000,3550.000000,0.00000,0.000000,0.000000,0.000000,0.000000
75%,63.750000,18.000000,52000.000000,16425.000000,0.00000,0.000000,0.000000,0.000000,1.000000
max,98.000000,23.000000,320000.000000,105000.000000,1.00000,1.000000,1.000000,1.000000,1.000000

In [84]:

X = upd_df.drop('Views', axis=1)

# print(X)
Y = upd_df['Views']
# print(Y)
# print(X.shape)
X.describe()

,Title_Length,Upload_Hour,Current_Subscribers,Color_Blue,Color_Green,Color_Orange,Color_Purple,Color_Red
count,150.000000,150.000000,150.000000,150.00000,150.000000,150.000000,150.000000,150.000000
mean,51.500000,13.413333,36403.666667,0.20000,0.166667,0.133333,0.100000,0.400000
std,19.813476,5.670111,56433.106384,0.40134,0.373927,0.341073,0.301005,0.491539
min,15.000000,1.000000,50.000000,0.00000,0.000000,0.000000,0.000000,0.000000
25%,36.000000,9.250000,2025.000000,0.00000,0.000000,0.000000,0.000000,0.000000
50%,50.000000,15.000000,11750.000000,0.00000,0.000000,0.000000,0.000000,0.000000
75%,63.750000,18.000000,52000.000000,0.00000,0.000000,0.000000,0.000000,1.000000
max,98.000000,23.000000,320000.000000,1.00000,1.000000,1.000000,1.000000,1.000000

In [85]:
model = LinearRegression()
model.fit(X, Y)

LinearRegression()

In [97]:
X_test = [ [ 69, 13, 6969, 0, 0, 1, 0, 0 ] ]
X_test2 = [ [ 24, 17, 60969, 0, 0, 0, 0, 1 ] ]

In [98]:
Y_pred = model.predict(X_test2)
print(f"\nyour video will get -> {Y_pred.round()} views!\n")

your video will get -> [19912.] views!

d:\Programming\my_python\.venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

Read youtube_data.csv | Data cleaning - removed Video_ID column 
| Dropped Thumbnail_Color -> converted each color into separate column ( 0 or 1) | here we go! our first ever prediction | the restult is - According the our model a video of title length 69, uploaded on 13, with 6969 subs chanel, with thumbnail color orange will get -> 1326 views