In [30]:
import pandas as pd
from sklearn.linear_model import LinearRegression

In [ ]:
df = pd.read_csv('youtube_data.csv')
print(df)

    Video_ID  Title_Length  Upload_Hour Thumbnail_Color  Current_Subscribers  \
0          1            45           17             Red                50000
1          2            32           10            Blue                 1500
2          3            60           18             Red               300000
3          4            25            3           Green                  200
4          5            55           16             Red                12000
5          6            40           12          Orange                 5000
6          7            85            9            Blue               100000
7          8            30           19             Red                 2500
8          9            50           14           Green                45000
9         10            95           22          Purple                  100
10        11            20            8             Red                80000
11        12            65           17            Blue                 2000
12        13            48           15          Orange               150000
13        14            35           11             Red                 6000
14        15            15            4           Green                  300
15        16            70           18             Red                55000
16        17            52           13            Blue                22000
17        18            41           20          Purple                 1200
18        19            63           16             Red                90000
19        20            28            7           Green                 4000
20        21            58           19             Red                11000
21        22            33            2            Blue                  800
22        23            75           15          Orange                67000
23        24            44           18             Red                25000
24        25            39           12           Green                 9000
25        26            90           23          Purple                   50
26        27            47           17             Red                40000
27        28            55           10            Blue                 3000
28        29            62           14             Red                18000
29        30            22            6          Orange                  500

    Views
0   12500
1     400
2   85000
3      50
4    3200
5    1100
6   18000
7     900
8    8500
9      30
10  21000
11    550
12  42000
13   1800
14     20
15  16000
16   5100
17    350
18  28000
19    800
20   3100
21    150
22  19500
23   7200
24   2100
25     10
26  11000
27    750
28   4500
29    120

# Red, Blue, Green, Orange, Purple

In [10]:
new_df = df.drop('Video_ID', axis=1)
print(new_df)

    Title_Length  Upload_Hour Thumbnail_Color  Current_Subscribers  Views
0             45           17             Red                50000  12500
1             32           10            Blue                 1500    400
2             60           18             Red               300000  85000
3             25            3           Green                  200     50
4             55           16             Red                12000   3200
5             40           12          Orange                 5000   1100
6             85            9            Blue               100000  18000
7             30           19             Red                 2500    900
8             50           14           Green                45000   8500
9             95           22          Purple                  100     30
10            20            8             Red                80000  21000
11            65           17            Blue                 2000    550
12            48           15          Orange               150000  42000
13            35           11             Red                 6000   1800
14            15            4           Green                  300     20
15            70           18             Red                55000  16000
16            52           13            Blue                22000   5100
17            41           20          Purple                 1200    350
18            63           16             Red                90000  28000
19            28            7           Green                 4000    800
20            58           19             Red                11000   3100
21            33            2            Blue                  800    150
22            75           15          Orange                67000  19500
23            44           18             Red                25000   7200
24            39           12           Green                 9000   2100
25            90           23          Purple                   50     10
26            47           17             Red                40000  11000
27            55           10            Blue                 3000    750
28            62           14             Red                18000   4500
29            22            6          Orange                  500    120

In [16]:
color_df = pd.get_dummies( new_df['Thumbnail_Color'], prefix='Color',  dtype=int)
print(color_df)

    Color_Blue  Color_Green  Color_Orange  Color_Purple  Color_Red
0            0            0             0             0          1
1            1            0             0             0          0
2            0            0             0             0          1
3            0            1             0             0          0
4            0            0             0             0          1
5            0            0             1             0          0
6            1            0             0             0          0
7            0            0             0             0          1
8            0            1             0             0          0
9            0            0             0             1          0
10           0            0             0             0          1
11           1            0             0             0          0
12           0            0             1             0          0
13           0            0             0             0          1
14           0            1             0             0          0
15           0            0             0             0          1
16           1            0             0             0          0
17           0            0             0             1          0
18           0            0             0             0          1
19           0            1             0             0          0
20           0            0             0             0          1
21           1            0             0             0          0
22           0            0             1             0          0
23           0            0             0             0          1
24           0            1             0             0          0
25           0            0             0             1          0
26           0            0             0             0          1
27           1            0             0             0          0
28           0            0             0             0          1
29           0            0             1             0          0

In [39]:
upd_df = pd.concat( [ new_df.drop('Thumbnail_Color', axis=1), color_df ], axis=1 )

# print(upd_df)

In [22]:
upd_df.describe()

,Title_Length,Upload_Hour,Current_Subscribers,Views,Color_Blue,Color_Green,Color_Orange,Color_Purple,Color_Red
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000
mean,49.300000,13.500000,36705.000000,9791.000000,0.200000,0.166667,0.133333,0.100000,0.400000
std,20.551282,5.563117,62173.633881,17397.272745,0.406838,0.379049,0.345746,0.305129,0.498273
min,15.000000,2.000000,50.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,33.500000,10.000000,1625.000000,437.500000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,47.500000,14.500000,10000.000000,2600.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,61.500000,17.750000,48750.000000,12125.000000,0.000000,0.000000,0.000000,0.000000,1.000000
max,95.000000,23.000000,300000.000000,85000.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [48]:
# X = [ upd_df['Title_Length'], upd_df['Upload_Hour'], upd_df['Current_Subscribers'], upd_df['Color_Blue'], upd_df['Color_Green'], upd_df['Color_Orange'], upd_df['Color_Purple'], upd_df['Color_Red'] ]

X = pd.concat( [ upd_df.drop('Views', axis=1) ])

# print(X)
Y = upd_df['Views']
# print(Y)
# print(X.shape)
X.describe()

,Title_Length,Upload_Hour,Current_Subscribers,Color_Blue,Color_Green,Color_Orange,Color_Purple,Color_Red
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000
mean,49.300000,13.500000,36705.000000,0.200000,0.166667,0.133333,0.100000,0.400000
std,20.551282,5.563117,62173.633881,0.406838,0.379049,0.345746,0.305129,0.498273
min,15.000000,2.000000,50.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,33.500000,10.000000,1625.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,47.500000,14.500000,10000.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,61.500000,17.750000,48750.000000,0.000000,0.000000,0.000000,0.000000,1.000000
max,95.000000,23.000000,300000.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [47]:
model = LinearRegression()
model.fit(X, Y)

LinearRegression()

In [51]:
X_test = [ [ 69, 13, 6969, 0, 0, 1, 0, 0 ] ]

In [53]:
Y_pred = model.predict(X_test)
print(Y_pred)

[1326.23585594]

d:\Programming\my_python\.venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

Read youtube_data.csv | Data cleaning - removed Video_ID column 
| Dropped Thumbnail_Color -> converted each color into separate column ( 0 or 1) |